### Standard Background


SpriteWindowSetBackgroundTopColor(0, 0.4, 1);
SpriteWindowSetBackgroundBottomColor(0.00, 0.00, 0.00);

screen_width = Window.GetWidth();
screen_height = Window.GetHeight();

label_image = Image("label.png");
label_sprite = Sprite(label_image);
label_sprite.SetX(Window.GetWidth()  / 2  - ImageGetWidth(label_image) / 2);
label_sprite.SetY(Window.GetHeight() / 2 - ImageGetHeight(label_image) / 2);
label_sprite.SetZ(10000);
label_sprite.SetOpacity(0.7);

index = 0;
while (1){
    index_string = index;
    if (index < 10) index_string = "0" + index_string;
    frame_image[index] = ImageNew("throbber-" + index_string + ".png");
    if (!frame_image[index]) break;

    index++;
    }
frame_count = 55;
frame_index = 10;

frame_count1 = 55;
frame_index1 = 0;

frame_count2 = 55;
frame_index2 = 20;

throbber_sprite = SpriteNew();
throbber_sprite1 = SpriteNew();
throbber_sprite2 = SpriteNew();

fun refresh (){
    if (status == "normal"){
        frame_index += 0.2;
        frame_index %= frame_count;
        int_frame_index = MathInt(frame_index);

        frame_index1 += 0.2;
        frame_index1 %= frame_count;
        int_frame_index1 = MathInt(frame_index1);

        frame_index2 += 0.2;
        frame_index2 %= frame_count;
        int_frame_index2 = MathInt(frame_index2);

        scaled = frame_image[int_frame_index];
        scaled1 = frame_image[int_frame_index1];
        scaled2 = frame_image[int_frame_index2];

        index++;

        SpriteSetImage (throbber_sprite, scaled);
        SpriteSetX (throbber_sprite, SpriteWindowGetWidth() / 2 - ImageGetWidth(scaled)  / 2);
        SpriteSetY (throbber_sprite, SpriteWindowGetHeight() / 2 - ImageGetHeight(scaled) / 2);
        SpriteSetOpacity (throbber_sprite, 1);

        SpriteSetImage (throbber_sprite1, scaled1);
        SpriteSetX (throbber_sprite1, SpriteWindowGetWidth() / 2 + ImageGetWidth(scaled1)  / 2 );
        SpriteSetY (throbber_sprite1, SpriteWindowGetHeight() / 2 - ImageGetHeight(scaled1) / 2);
        SpriteSetOpacity (throbber_sprite1, 1);

        SpriteSetImage (throbber_sprite2, scaled2);
        SpriteSetX (throbber_sprite2, SpriteWindowGetWidth() / 2 - ImageGetWidth(scaled2)  / 2 - ImageGetWidth(scaled2));
        SpriteSetY (throbber_sprite2, SpriteWindowGetHeight() / 2 - ImageGetHeight(scaled2) / 2);
        SpriteSetOpacity (throbber_sprite2, 1);
        }
    else{
        SpriteSetOpacity (throbber_sprite, 0);
        SpriteSetOpacity (throbber_sprite1, 0);
        SpriteSetOpacity (throbber_sprite2, 0);
        }
    }

PlymouthSetRefreshFunction (refresh);

status = "normal";

#----------------------------------------- Message --------------------------------
message_sprite = Sprite();
message_sprite.SetPosition(10, 10, 10000);

fun message (text)
{
	my_image = Image.Text(text, 0.6, 0.6, 0.6);
	message_sprite.SetImage(my_image);
	message_sprite.SetX(Window.GetWidth ()  / 2 - my_image.GetWidth()  / 2);
	message_sprite.SetY(Window.GetHeight () - my_image.GetHeight());
	message.sprite.SetZ(11);
    }

Plymouth.SetMessageFunction(message);
